spring:
  application:
    name: delivery

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: delivery
    password: delivery1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

jwt:
  secret-key: ZR1oEz01qa7AKFzCfLoS8SnUvDxdNvY1GkuzJit51CB
  access-token-expiration: 30m
  refresh-token-expiration: 14d
